--- #YAML:1.0
name:                savelogs
version:             1.92
abstract:            save/rotate/delete log files nicely
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Scott Wiersdorf <scott@perlcode.org>
